### ISSUE TITLE
Load custom formats

### ISSUE THREAD

**Issue by pma** [kennellroxco/xlsxir#17]
Sample from xl/styles.xml:

```xml
<numFmts count="4"><numFmt numFmtId="164" formatCode="GENERAL"/><numFmt numFmtId="165" formatCode="#,##0"/><numFmt numFmtId="166" formatCode="#,##0.00"/><numFmt numFmtId="167" formatCode="YYYY/MM/DD"/></numFmts><fonts count="4">
```

Current implementation raises here: https://github.com/kennellroxco/xlsxir/blob/master/lib/xlsxir/parse.ex#L73

```iex
** (RuntimeError) Unknown style type: 164.
    (xlsxir) lib/xlsxir/parse.ex:73: anonymous fn/1 in Xlsxir.Parse.num_style/1
    (elixir) lib/enum.ex:1088: Enum."-map/2-lists^map/1-0-"/2
    (xlsxir) lib/xlsxir.ex:44: Xlsxir.extract/3
```

**Comment by kennellroxco** [comment]
A `numFmtId` equal to or greater than 164 is a custom format which can vary from system to system, so I haven't figured out a way yet to automate that. You have two options, first you can reformat your worksheet to standard formats prior to parsing, or you can update the code on your local instance to include your custom formats. I will be updating the documentation to include detailed instructions on how to make these changes. 

`Xlsxir.Parse.num_style/1` is set up to return `nil` in case of an integer or float and `'d'` for cells containing an Excel date serial number. In your case, IDs 164 - 166 appear to be integers or floats and 167 a date. To fix, insert the following after line 72:
```
i when i in 164..166 -> nil
167 -> 'd'
```
I will continue to look for a solution to the custom formats, and will include instructions to correct manually as well as ensure I have all standard IDs covered in the next release. 

Let me know if that doesn't work or you have further questions.

**Comment by kennellroxco** [comment]
On second thought, I have an idea on how to automate the custom formats. I'm working on it on a separate branch. @pma would you be up for pulling it down and testing once I'm finished?

**Comment by pma** [comment]
@kennellroxco Glad to help you test the feature. Let me know when you finish it.

**Comment by kennellroxco** [comment]
@pma I'm ready for a test run. The branch is labeled `custom_format`. Thanks for the help! Do your best to break it :)

**Comment by kennellroxco** [comment]
I went ahead and did some testing and things seem to be working well. I'm about to publish the changes as version 0.0.4 on Hex. Let me know if you have any other issues with it.

**Comment by pma** [comment]
@kennellroxco Sorry for the delay. I was able to load the set of Excel files after a change to `Xlsxir.Format.format_cell_value/2`. Xlsxir.extract was failing with error:

```iex
** (RuntimeError) Unmapped attribute n. Unable to process
    (xlsxir) lib/xlsxir/format.ex:84: Xlsxir.Format.format_cell_value/2
    (elixir) lib/enum.ex:1088: Enum."-map/2-lists^map/1-0-"/2
    (elixir) lib/enum.ex:1088: Enum."-map/2-lists^map/1-0-"/2
    (elixir) lib/enum.ex:1088: Enum."-map/2-lists^map/1-0-"/2
    (elixir) lib/enum.ex:1088: Enum."-map/2-lists^map/1-0-"/2
``` 

Adding `['n',   nil,  n]  -> list_to_number(n)` to the case statement in format_cell_value solved the problem, though I'm not sure why it is 'n' and not 'd'.

```elixir
  defp list_to_number(list) do
    try do
      List.to_float(list)
    rescue
      ArgumentError ->
        List.to_integer(list)
    end
  end
```

I have a date column and a numeric column in the Excel and both fall into this case.

I'm not sure the way dates are handled will work everytime. The cell value of a date is a number, so it could either be a date or a true decimal. Only the format gives any hint it is a date.

**Comment by kennellroxco** [comment]
@pma Can you tell me what the format type is in excel for both of the columns you mentioned that were failing with an `'n'`?

**Comment by pma** [comment]
The workbook xml actually has `t="n"`. Here's a gist with the workbooks and styles: https://gist.github.com/pma/1c1ccce750ca2b077f31a4389d6f7880

**Comment by kennellroxco** [comment]
Ok, I see what's going on. `t` is actually the data type (`'n'` for number, `'s'` for string, `'e'` for error, etc.) and `s` is the style index. I hadn't run into a data type of `'n'` yet as most of the situations I have seen have just left that set to `nil` for numbers. I see you're using a different language though (Portuguese?), so that may be the reason.

If you look at your `style.xml` starting at `line 75`, you'll see 5 `numFmtId`s beginning with `164`. The style index (`s`) on the worksheet is the index that points to the `numFmtId` in `style.xml` (i.e. `164` is at index 0, `167` is at index 3). So for `sheet1.xml` at `line 51`, you have cell `E2` with a style index of `3` and a data type of `'n'` which directs the date serial number of `42505` on `line 72`. The style index of `3` points to `numFmtId` of `167`, which then points to the `formatCode` of `"YYYY/MM/DD"` (`line 7` of `styles.xml`). 

Super confusing, I know...but I think all we need to fix it is to add the following two lines to `Xlsxir.Format.format_cell_value/2`:

```
['n', nil, n] -> convert_char_number(n)
['n', 'd', d] -> Xlsxir.ConvertDate.from_excel(d)
```

Give that a shot and let me know if that fixes the issue and if so, I'll include with the next release.

Thanks for taking the time to look at it!

**Comment by pma** [comment]
@kennellroxco Yes, it's Portuguese, and I created this .xlsx in LibreOffice.

Adding the `convert_char_number` case fixes the exception. The second is never matched, because the date column also matches ['n', nil, n].

These are the intermediate results:

```iex
iex(1)> {:ok, file} = Unzip.validate_path(path)  

iex(2)> strings = Parse.shared_strings(file)   
["Descritivo", "N.º Aluno", "Nome", "Montante", "Data Limite", "Teste A",
 "Teste B", "Teste C", "Ano", "Mês", "Dia Limite"]

iex(3)> styles = Parse.num_style(file)         
[nil, nil, nil, nil, nil]

iex(4)> parsed = Parse.worksheet(file, 0, styles)
[[A1: ['s', nil, '0'], B1: ['s', nil, '1'], C1: ['s', nil, '2'],
  D1: ['s', nil, '3'], E1: ['s', nil, '4']],
 [A2: ['str', nil, 'Mensalidade de Maio de 2016'], B2: ['n', nil, '1001'],
  C2: ['s', nil, '5'], D2: ['n', nil, '10000'], E2: ['n', nil, '42505']],
 [A3: ['str', nil, 'Mensalidade de Maio de 2016'], B3: ['n', nil, '1002'],
  C3: ['s', nil, '6'], D3: ['n', nil, '15000'], E3: ['n', nil, '42505']],
 [A4: ['str', nil, 'Mensalidade de Maio de 2016'], B4: ['n', nil, '1003'],
  C4: ['s', nil, '7'], D4: ['n', nil, '12333.34'], E4: ['n', nil, '42505']]]

iex(5)> Format.prepare_output(parsed, strings, :rows)
[["Descritivo", "N.º Aluno", "Nome", "Montante", "Data Limite"],
 ["Mensalidade de Maio de 2016", 1001, "Teste A", 10000, 42505],
 ["Mensalidade de Maio de 2016", 1002, "Teste B", 15000, 42505],
 ["Mensalidade de Maio de 2016", 1003, "Teste C", 12333.34, 42505]]
```

I think we would need to include the formatCode in the structure resulting from Parse.worksheet. Still it would take some heuristics to look at "YYYY/MM/DD" and determine is "should" be a date.

Looking at Apache POI, checking if a cell is a date seems quite convoluted: http://grepcode.com/file/repo1.maven.org/maven2/org.apache.poi/poi/3.9/org/apache/poi/ss/usermodel/DateUtil.java#DateUtil.isADateFormat%28int%2Cjava.lang.String

I can work around dates being extracted as a number. With some post-processing and knowing that the last column is a date, the conversion can be done in the next stage.

**Comment by kennellroxco** [comment]
Do me a favor and try one last thing for me. Adjust the regex on `line 108` of `Xlsxir.Parse` from `~r/[dhmsy]/` to `~r/[dhmsy]/i` making it case insensitive and see if that fixes the issue. Thanks again!

**Comment by pma** [comment]
@kennellroxco With the change it now correctly parses a date. A limitation is that if we set it to a datetime value, we can only extract the year, month, day part. 

```iex
iex(7)> styles = Parse.num_style(file)       
[nil, nil, nil, 'd', nil]

iex(8)> parsed = Parse.worksheet(file, 0, styles)
[[A1: ['s', nil, '0'], B1: ['s', nil, '1'], C1: ['s', nil, '2'],
  D1: ['s', nil, '3'], E1: ['s', 'd', '4']],
 [A2: ['str', nil, 'Mensalidade de Maio de 2016'], B2: ['n', nil, '1001'],
  C2: ['s', nil, '5'], D2: ['n', nil, '10000'], E2: ['n', 'd', '42505']],
 [A3: ['str', nil, 'Mensalidade de Maio de 2016'], B3: ['n', nil, '1002'],
  C3: ['s', nil, '6'], D3: ['n', nil, '15000'], E3: ['n', 'd', '42505']],
 [A4: ['str', nil, 'Mensalidade de Maio de 2016'], B4: ['n', nil, '1003'],
  C4: ['s', nil, '7'], D4: ['n', nil, '12333.34'], E4: ['n', 'd', '42505']]]

iex(9)> Format.prepare_output(parsed, strings, :rows)
[["Descritivo", "N.º Aluno", "Nome", "Montante", "Data Limite"],
 ["Mensalidade de Maio de 2016", 1001, "Teste A", 10000, {2016, 5, 15}],
 ["Mensalidade de Maio de 2016", 1002, "Teste B", 15000, {2016, 5, 15}],
 ["Mensalidade de Maio de 2016", 1003, "Teste C", 12333.34, {2016, 5, 15}]]
```

**Comment by kennellroxco** [comment]
Thanks @pma. That's a good suggestion, I'll add it to the list for future development.
