### ISSUE TITLE
Ignore empty cells

### ISSUE THREAD

**Issue by taniadaniela** [kennellroxco/xlsxir#24]
Hi. I need to parse a sheet that contains empty cells, but I can't ignore them, I need to obtain some empty char or nil option. Is there some way to have this behavior?  I saw that you added the functionality  of ignoring empty cells in the last version.

**Comment by kennellroxco** [comment]
Yes, that was a temporary fix. I actually just finished the code to fix that issue and will be publishing it shortly. Empty cells will now be represented as nil. Once published, please let me know if you have any additional issues!

**Comment by kennellroxco** [comment]
Changes are live. Let me know how it goes.

**Comment by taniadaniela** [comment]
It works perfectly.. thanks!
