### ISSUE TITLE
not adding xlsxir to application function

### ISSUE THREAD

**Issue by taniadaniela** [kennellroxco/xlsxir#26]
Hello, I'm having the doubt if isn't necessary to add xlsxir to application function into mix.exs? 
As in application is supposed to be added all the stuff you need in production..

**Comment by kennellroxco** [comment]
Currently you do not need to add Xlsxir to the application function in `mix.exs`. As long as you have it listed as a dependency you'll have access to it in your application. Are you having an issue using it? If so, could you give me some more specifics regarding the details of the issue? Thanks.

**Comment by taniadaniela** [comment]
No, I'm not having any issue, it was just a doubt about it. I'm on the develop process yet, I haven't test the app in production env. I'll let you know how it works there. Thanks for the feedback. 👍
