### ISSUE TITLE
Plans for Excel Export?

### ISSUE THREAD

**Issue by schaary** [kennellroxco/xlsxir#3]
I need a tool to export into Excel file format. Do you have any plans to extend the project by an export feature?

**Comment by kennellroxco** [comment]
Yes, once I get the parsing performance issues wrapped up (which I'm about finished with) I'll start looking at export functionality with basic formatting.

**Comment by apcxiii** [comment]
Hi, I don't parse a text with ampersand i.e "http://domain.com?param1=aaa&param2=two"

**Comment by kennellroxco** [comment]
Closing for now. I'll be working on export functionality soon.
