### ISSUE TITLE
Export to XLSX

### ISSUE THREAD

**Issue by brandonparsons** [kennellroxco/xlsxir#30]
Hi there,

I'm looking around for an Elixir library that can export data to Excel format.  You have this listed in your development goals:

> Export functionality to .xlsx file type with formatting options

I'm just wondering how actively that's being worked? Do you know of any libraries in the Elixir ecosystem at all that can do this right now?

**Comment by kennellroxco** [comment]
I do plan on eventually getting to that, however, I haven't started yet.
There is one out there named elixlsx that exports to excel. I haven't used
it so I can't vouch for it but I'd give it a try.

**Comment by brandonparsons** [comment]
Thanks for the hint on `elixlsx`! I'll close this issue now, as it's obviously on your roadmap already :)
