### ISSUE TITLE
inlineStr type not parsed

### ISSUE THREAD

**Issue by pedrogarrett** [kennellroxco/xlsxir#31]
cell value of inlineStr is not parsed... adding:

   ['inlineStr',   _,  s]  -> List.to_string(s)

to the format_cell_value function makes it work, but I'm not sure if that's the correct solution.

**Comment by kennellroxco** [comment]
Thanks @pedrogarrett. Can you tell me what program you are using (i.e. Excel, LibreOffice, etc.)? I haven't run into that type before.

**Comment by kennellroxco** [comment]
Ok, you're proposal will work for now until I have time to explore that gem further. I'm currently making some minor improvements so I'll add that fix and push out in an updated version ASAP. Thanks for pointing it out! I'll close this issue once the change is published on Hex.

**Comment by kennellroxco** [comment]
Publishing update on Hex.
