### ISSUE TITLE
Parsed Row/Column values leaks into subsequent rows and corrupt parsed data

### ISSUE THREAD

**Issue by pikender** [kennellroxco/xlsxir#35]
**Observation but might not be the actual cause**

When using merged cells with partially colored text, Row values wrongly leaked into subsequent rows and data from parsing is corrupted.

**Sample Text (is Bold, has Green in green color and Blue in Blue color)**

    Detailed Info, Green are mandatory fields, Blue are optional ones

Here *Green are mandatory fields, Blue are optional ones* are wrongly parsed as next row values and corrupts values for next row and further

**Sample Xlsx with parsing problem**

[sample_with_color_and_merged_cells.xlsx](https://github.com/kennellroxco/xlsxir/files/636577/sample_with_color_and_merged_cells.xlsx)

**IEX Log and parsed data**

```elixir
iex(1)> file_path = "/home/pikender/sample_with_color_and_merged_cells.xlsx"
"/home/pikender/sample_with_color_and_merged_cells.xlsx"
iex(2)> Xlsxir.extract(file_path, 0, true)                                                             
{:ok, [0, 0, 0, 123158]}
iex(3)> Xlsxir.get_list
[["Profile Info", nil, nil, nil], ["Full Name", "First Name", "Last Name", nil],
 [nil, nil, nil, nil],
 ["Detailed Info, ", nil, nil, nil, nil, nil, nil, nil, nil],
 ["Green", " are mandatory fields, ", "Blue", " are optional ones", "Name",
  "Phone Number", "Country", "City", "State"], ["Address 1"]]
iex(50)> Xlsxir.close   
:ok
```

**Expected**

Even, if doesn't match below parsing but altleast should prevent corruption of other rows data and parse properly

```
[
  ["Profile Info", nil, nil, nil],
  ["Full Name", "First Name", "Last Name", nil],
  [nil, nil, nil, nil],
  ["Detailed Info, Green are mandatory fields, Blue are optional ones", nil, nil, nil, nil, nil, nil, nil, nil],
  ["Name", "Phone Number", "Country", "City", "State", "Address 1", "Address 2", "Zip Code", "Landmark"],
  ["Pikender"]
]
```

**Actual**
```
[
  ["Profile Info", nil, nil, nil],
  ["Full Name", "First Name", "Last Name", nil],
  [nil, nil, nil, nil],
  ["Detailed Info, ", nil, nil, nil, nil, nil, nil, nil, nil],
  ["Green", " are mandatory fields, ", "Blue", " are optional ones", "Name", "Phone Number", "Country", "City", "State"],
  ["Address 1"]
]
```

Let me know if any more info needed

**Comment by pikender** [comment]
I tried narrowing down the possible cause more and found that **Mixed formatting in same cell leads to unexpected results**

**Mixed Formatting Examples**

- All words Simple but one **Bold**
- All words Simple but one *Italic*
- All words in Black Color but one in Green or Blue

Attaching a xlsx which reproduces the anomaly better using above mixed formatting examples

[sample_with_mixed_formatting_in_cell.xlsx](https://github.com/kennellroxco/xlsxir/files/636672/sample_with_mixed_formatting_in_cell.xlsx)

```elixir
iex(1)> file_path = "/home/pikender/sample_with_color_and_merged_cells.xlsx"
"/home/pikender/sample_with_color_and_merged_cells.xlsx"
iex(2)> Xlsxir.extract(file_path, 0, true);Xlsxir.get_list |> IO.inspect;  Xlsxir.close
[["Profile Info", nil, nil, nil], ["Full Name", "First Name", "Last Name", nil],
 [nil, nil, nil, nil],
 ["Detailed Info, Green are mandatory fields, Blue are optional ones", nil, nil,
  nil, nil, nil, nil, nil, nil],
 ["Name", "Phone Number", "Country", "City", "State", "Address 1", "Address 2",
  "Zip Code", "Landmark"], ["Pikender"]]
:ok
iex(3)> Xlsxir.extract(file_path, 0, true);Xlsxir.get_list |> IO.inspect;  Xlsxir.close
[["Profile Info", nil, nil, nil], ["Full Name", "First Name", "Last Name", nil],
 [nil, nil, nil, nil],
 ["Detailed Info, ", nil, nil, nil, nil, nil, nil, nil, nil],
 ["Green", " are mandatory fields, Blue are optional ones", "Name",
  "Phone Number", "Country", "City", "State", "Address 1", "Address 2"],
 ["Zip Code"]]
:ok
```

Hope it helps

**Comment by kennellroxco** [comment]
Thanks for the info. I'll take a look.

**Comment by kennellroxco** [comment]
@pikender I figured out the issue, just working on a solution.

**Comment by kennellroxco** [comment]
@pikender I think I got it. Please pull, test and let me know how it goes. Thanks!

**Comment by pikender** [comment]
@kennellroxco seems to parse well with samples I have :+1: :blush:

**Comment by kennellroxco** [comment]
Closing this issue. Let me know if you have any other problems. Thanks!
