### ISSUE TITLE
argument error     (stdlib) :ets.new

### ISSUE THREAD

**Issue by Lioshaq** [kennellroxco/xlsxir#47]
Hi I'm trying to read a xlsx but always get the same error 
** (ArgumentError) argument error
    (stdlib) :ets.new(:styles, [:set, :protected, :named_table])
             lib/xlsxir/state_manager.ex:199: Xlsxir.Style.new/0
             lib/xlsxir/sax_parser.ex:52: Xlsxir.SaxParser.parse/3
    (elixir) lib/enum.ex:645: Enum."-each/2-lists^foreach/1-0-"/2
    (elixir) lib/enum.ex:645: Enum.each/2
             lib/xlsxir.ex:179: Xlsxir.do_multi_extract/3
with extract and peek get the same error can you suggest a solution?

**Comment by kennellroxco** [comment]
Hello @Lioshaq. Can you tell me if this happens in a new `iex` session when you first try to parse a worksheet? Or only after the first attempt? Could you please crack open your .xlsx file and list the contents of the `/xl` folder? Thanks!
